window.C_ROAD_DATA = {
  keywords: ["auto","break","case","char","const","continue","default","do",
    "double","else","enum","extern","float","for","goto","if","inline","int",
    "long","register","restrict","return","short","signed","sizeof","static",
    "struct","switch","typedef","union","unsigned","void","volatile","while",
    "_Bool","_Complex","_Imaginary","_Alignas","_Alignof","_Atomic","_Generic",
    "_Noreturn","_Static_assert","_Thread_local"],

  types: ["size_t","ssize_t","ptrdiff_t","int8_t","int16_t","int32_t","int64_t",
    "uint8_t","uint16_t","uint32_t","uint64_t","bool","FILE"],

  macros: ["NULL","EOF","EXIT_SUCCESS","EXIT_FAILURE","SEEK_SET","SEEK_CUR",
    "SEEK_END","stdin","stdout","stderr","true","false","M_PI","M_E"],

  headers: ["stdio.h","stdlib.h","string.h","math.h","ctype.h","time.h",
    "stdbool.h","stdint.h","stddef.h","stdarg.h","assert.h","errno.h",
    "limits.h","float.h","signal.h","setjmp.h","locale.h","wchar.h",
    "inttypes.h","complex.h","stdatomic.h","threads.h","unistd.h","fcntl.h",
    "sys/types.h","sys/stat.h","pthread.h","dirent.h"],

  functions: {
    printf:     { sig: "int printf(const char *fmt, ...)", h: "stdio.h" },
    fprintf:    { sig: "int fprintf(FILE *f, const char *fmt, ...)", h: "stdio.h" },
    sprintf:    { sig: "int sprintf(char *s, const char *fmt, ...)", h: "stdio.h" },
    snprintf:   { sig: "int snprintf(char *s, size_t n, const char *fmt, ...)", h: "stdio.h" },
    scanf:      { sig: "int scanf(const char *fmt, ...)", h: "stdio.h" },
    fscanf:     { sig: "int fscanf(FILE *f, const char *fmt, ...)", h: "stdio.h" },
    sscanf:     { sig: "int sscanf(const char *s, const char *fmt, ...)", h: "stdio.h" },
    fopen:      { sig: "FILE *fopen(const char *path, const char *mode)", h: "stdio.h" },
    fclose:     { sig: "int fclose(FILE *f)", h: "stdio.h" },
    fread:      { sig: "size_t fread(void *p, size_t sz, size_t n, FILE *f)", h: "stdio.h" },
    fwrite:     { sig: "size_t fwrite(const void *p, size_t sz, size_t n, FILE *f)", h: "stdio.h" },
    fgets:      { sig: "char *fgets(char *s, int n, FILE *f)", h: "stdio.h" },
    fputs:      { sig: "int fputs(const char *s, FILE *f)", h: "stdio.h" },
    fgetc:      { sig: "int fgetc(FILE *f)", h: "stdio.h" },
    fputc:      { sig: "int fputc(int c, FILE *f)", h: "stdio.h" },
    fseek:      { sig: "int fseek(FILE *f, long off, int whence)", h: "stdio.h" },
    ftell:      { sig: "long ftell(FILE *f)", h: "stdio.h" },
    rewind:     { sig: "void rewind(FILE *f)", h: "stdio.h" },
    feof:       { sig: "int feof(FILE *f)", h: "stdio.h" },
    ferror:     { sig: "int ferror(FILE *f)", h: "stdio.h" },
    perror:     { sig: "void perror(const char *s)", h: "stdio.h" },
    puts:       { sig: "int puts(const char *s)", h: "stdio.h" },
    putchar:    { sig: "int putchar(int c)", h: "stdio.h" },
    getchar:    { sig: "int getchar(void)", h: "stdio.h" },
    remove:     { sig: "int remove(const char *path)", h: "stdio.h" },
    rename:     { sig: "int rename(const char *o, const char *n)", h: "stdio.h" },
    fflush:     { sig: "int fflush(FILE *f)", h: "stdio.h" },
    setvbuf:    { sig: "int setvbuf(FILE *f, char *buf, int mode, size_t sz)", h: "stdio.h" },

    malloc:     { sig: "void *malloc(size_t n)", h: "stdlib.h" },
    calloc:     { sig: "void *calloc(size_t n, size_t sz)", h: "stdlib.h" },
    realloc:    { sig: "void *realloc(void *p, size_t n)", h: "stdlib.h" },
    free:       { sig: "void free(void *p)", h: "stdlib.h" },
    exit:       { sig: "void exit(int status)", h: "stdlib.h" },
    abort:      { sig: "void abort(void)", h: "stdlib.h" },
    atexit:     { sig: "int atexit(void (*fn)(void))", h: "stdlib.h" },
    atoi:       { sig: "int atoi(const char *s)", h: "stdlib.h" },
    atol:       { sig: "long atol(const char *s)", h: "stdlib.h" },
    atof:       { sig: "double atof(const char *s)", h: "stdlib.h" },
    strtol:     { sig: "long strtol(const char *s, char **e, int base)", h: "stdlib.h" },
    strtod:     { sig: "double strtod(const char *s, char **e)", h: "stdlib.h" },
    rand:       { sig: "int rand(void)", h: "stdlib.h" },
    srand:      { sig: "void srand(unsigned int seed)", h: "stdlib.h" },
    qsort:      { sig: "void qsort(void *b, size_t n, size_t s, int(*c)(const void*,const void*))", h: "stdlib.h" },
    bsearch:    { sig: "void *bsearch(const void *k, const void *b, size_t n, size_t s, int(*c)(const void*,const void*))", h: "stdlib.h" },
    abs:        { sig: "int abs(int x)", h: "stdlib.h" },
    labs:       { sig: "long labs(long x)", h: "stdlib.h" },
    getenv:     { sig: "char *getenv(const char *name)", h: "stdlib.h" },
    system:     { sig: "int system(const char *cmd)", h: "stdlib.h" },

    strlen:     { sig: "size_t strlen(const char *s)", h: "string.h" },
    strcpy:     { sig: "char *strcpy(char *d, const char *s)", h: "string.h" },
    strncpy:    { sig: "char *strncpy(char *d, const char *s, size_t n)", h: "string.h" },
    strcat:     { sig: "char *strcat(char *d, const char *s)", h: "string.h" },
    strncat:    { sig: "char *strncat(char *d, const char *s, size_t n)", h: "string.h" },
    strcmp:     { sig: "int strcmp(const char *a, const char *b)", h: "string.h" },
    strncmp:    { sig: "int strncmp(const char *a, const char *b, size_t n)", h: "string.h" },
    strchr:     { sig: "char *strchr(const char *s, int c)", h: "string.h" },
    strrchr:    { sig: "char *strrchr(const char *s, int c)", h: "string.h" },
    strstr:     { sig: "char *strstr(const char *h, const char *n)", h: "string.h" },
    strtok:     { sig: "char *strtok(char *s, const char *d)", h: "string.h" },
    strdup:     { sig: "char *strdup(const char *s)", h: "string.h" },
    memcpy:     { sig: "void *memcpy(void *d, const void *s, size_t n)", h: "string.h" },
    memmove:    { sig: "void *memmove(void *d, const void *s, size_t n)", h: "string.h" },
    memset:     { sig: "void *memset(void *s, int c, size_t n)", h: "string.h" },
    memcmp:     { sig: "int memcmp(const void *a, const void *b, size_t n)", h: "string.h" },
    memchr:     { sig: "void *memchr(const void *s, int c, size_t n)", h: "string.h" },

    sqrt:       { sig: "double sqrt(double x)", h: "math.h" },
    pow:        { sig: "double pow(double x, double y)", h: "math.h" },
    exp:        { sig: "double exp(double x)", h: "math.h" },
    log:        { sig: "double log(double x)", h: "math.h" },
    log10:      { sig: "double log10(double x)", h: "math.h" },
    sin:        { sig: "double sin(double x)", h: "math.h" },
    cos:        { sig: "double cos(double x)", h: "math.h" },
    tan:        { sig: "double tan(double x)", h: "math.h" },
    asin:       { sig: "double asin(double x)", h: "math.h" },
    acos:       { sig: "double acos(double x)", h: "math.h" },
    atan:       { sig: "double atan(double x)", h: "math.h" },
    atan2:      { sig: "double atan2(double y, double x)", h: "math.h" },
    floor:      { sig: "double floor(double x)", h: "math.h" },
    ceil:       { sig: "double ceil(double x)", h: "math.h" },
    round:      { sig: "double round(double x)", h: "math.h" },
    fabs:       { sig: "double fabs(double x)", h: "math.h" },
    fmod:       { sig: "double fmod(double x, double y)", h: "math.h" },
    hypot:      { sig: "double hypot(double x, double y)", h: "math.h" },

    isalpha:    { sig: "int isalpha(int c)", h: "ctype.h" },
    isdigit:    { sig: "int isdigit(int c)", h: "ctype.h" },
    isalnum:    { sig: "int isalnum(int c)", h: "ctype.h" },
    isspace:    { sig: "int isspace(int c)", h: "ctype.h" },
    isupper:    { sig: "int isupper(int c)", h: "ctype.h" },
    islower:    { sig: "int islower(int c)", h: "ctype.h" },
    toupper:    { sig: "int toupper(int c)", h: "ctype.h" },
    tolower:    { sig: "int tolower(int c)", h: "ctype.h" }
  },

  snippets: {
    main: "int main(void) {\n    \n    return 0;\n}",
    for:  "for (int i = 0; i < n; i++) {\n    \n}",
    while:"while (condition) {\n    \n}",
    if:   "if (condition) {\n    \n}",
    ifelse:"if (condition) {\n    \n} else {\n    \n}",
    struct:"struct Name {\n    \n};",
    typedef:"typedef struct {\n    \n} Name;"
  }
};